/* (c) Infcroya contributors. See licence.txt in the root of the distribution for more information. */

#ifndef INFCROYA_ENTITIES_WEAPON_TYPES_H
#define INFCROYA_ENTITIES_WEAPON_TYPES_H

enum // infclass 0.6 copypaste
{
	INFWEAPON_NONE,
	INFWEAPON_HAMMER,
	INFWEAPON_GUN,
	INFWEAPON_SHOTGUN,
	INFWEAPON_GRENADE,
	INFWEAPON_RIFLE,
	INFWEAPON_NINJA,

	INFWEAPON_ENGINEER_RIFLE,

	INFWEAPON_SNIPER_RIFLE,

	INFWEAPON_SOLDIER_GRENADE,

	INFWEAPON_SCIENTIST_GRENADE,
	INFWEAPON_SCIENTIST_RIFLE,

	INFWEAPON_MEDIC_GRENADE,
	INFWEAPON_MEDIC_RIFLE,
	INFWEAPON_MEDIC_SHOTGUN,

	INFWEAPON_HERO_GRENADE,
	INFWEAPON_HERO_RIFLE,
	INFWEAPON_HERO_SHOTGUN,

	INFWEAPON_BIOLOGIST_SHOTGUN,
	INFWEAPON_BIOLOGIST_RIFLE,

	INFWEAPON_LOOPER_RIFLE,
	INFWEAPON_LOOPER_GRENADE,

	INFWEAPON_NINJA_HAMMER,
	INFWEAPON_NINJA_GRENADE,

	INFWEAPON_MERCENARY_GUN,
	INFWEAPON_MERCENARY_GRENADE,

	NB_INFWEAPON
};

#endif
